apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: addressbookapp
    spec:
      containers:
      - name: addressbook
        image: lerndevops/addressbook
        ports:
        - containerPort: 8080
---
# Node Port Service
apiVersion: apps/v1
kind: Service
metadata:
  labels:
    name: addressbook
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8090
  selector:
    name: addressbook
